### ISSUE TITLE
Exception when passing an 'icon' to YesNoBox

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [JorjMcKie/wxsimpleGUI#1]
I tried setting the 'icon' field in the call to YesNoBox and I was rewarded with:

```
C:\Python\Anaconda3\python.exe "C:/Python/PycharmProjects/My Handy Utilities/MikesFastFolderCopy.py"
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/My Handy Utilities/MikesFastFolderCopy.py", line 155, in <module>
    sgui.YesNoBox('Mike\' Mega-Fast Copy', 'Use TXT file for filenames?', icon='C:\\Python\\PycharmProjects\\My Handy Utilities\\CopyIcon.png')
  File "C:\Python\PycharmProjects\My Handy Utilities\wxsimpleGUI.py", line 152, in YesNoBox
    dlg.SetIcon(icon.GetIcon())
AttributeError: 'str' object has no attribute 'GetIcon'

Process finished with exit code 1

```
My code:
```
    use_text_file = sgui.YesNoBox('Mike\' Mega-Fast Copy', 'Use TXT file for filenames?',
                                  icon='C:\\Python\\PycharmProjects\\My Handy Utilities\\CopyIcon.png')
```
It's my first time working with icons so perhaps I am not using the right format?

**Comment by JorjMcKie** [comment]
This is just not designed into it. Currently it expects something of type PyEmbeddedImage, which has a method `GetIcon()`.
But I am uploading a new version which accepts three alternatives: type(wx.Icon), type(str) for a filename, and PyEmbeddedImage(*).

(*) PyEmbeddedImage are wx.Bitmaps implemented as Python code. Quite practical if you do not want to distribute extra image files with your application, but only Python code.

**Comment by JorjMcKie** [comment]
The following should work now:
```
user = sg.CodeBox(title, msg, icon="some.jpg")
```
