### ISSUE TITLE
I would like to propose a FlexForm capability....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [JorjMcKie/wxsimpleGUI#2]
I've designed a few options for what I'm calling FlexForms.

I want to give users the ability to make a form using Text to describe the form.
The goal, a single line of code per 'row' or item in the form.

I am suggesting that each of these rows be limited to this two simple formats:
```
`Label            Entry box                 Button`
Button          Button
```
A simple 'Copy Folders' app is a good example.
For this kind of GUI, you would want 2 inputs, the source and destination folders.

Here's one way of doing it using TEXT to specify the rows:
```
    my_form = sgui.FlexForm('This is my title', 'This is message text like Please Enter Folders')
    
    my_form.AddRow(f'<LABEL(Please enter source folder)>            <ENTRY(Default Source Folder)>      <BUTTON_GET_FOLDER(Button Text)>')
    my_form.AddRow(f'<LABEL(Please entery destination folder)>      <ENTRY(Default Dest Folder)>        <BUTTON_GET_FOLDER(Browse)>')
    my_form.AddRow(f'<BUTTON_SUBMIT>    <BUTTON_CANCEL>')

    results = my_form.show()
```

The caller specifies 'elements' that make up row.  The first row asks for the Source Folder. Normally you would have text explaining what the text entry box is for. Then the single line text entry box.  Finally, there's a 'Browse for folder' button at the end.

Each element in the FlexForm spec string has this format:
`<FLEX_ELEMENT_NAME(default value)> 
`
We could also say that any text within that format string is inserted at the appropriate locations. This would remove the need for a <LABEL> Element.  The first row would then read:
`    my_form.AddRow(f'Please enter source folder                     <ENTRY(Default Source Folder)>      <BUTTON_GET_FOLDER(Button Text)>')`

Note that F-Strings are used!!  This requires Python 3.6.  Not a bad requirement.  I like living in the present , not the past :-)

By using F-strings, the user can embed variables into the string passed to  FlexForm.  Again using first row as an example. If one had a variable:
`     source_folder = '/user/mike/source
`And wanted to use that as the 'Default' value for the form, it can be written:
`    my_form.AddRow(f'Please enter source folder                     <ENTRY({source_folder})>      <BUTTON_GET_FOLDER(Button Text)>')`

There will be a bit of parsing work to be done in FlexForm, but that's MY problem, not the problem of the caller.  

My overall goal is to surprise the developer in how easy it is to throw a GUI front-end onto their normally boring command line application.

**Comment by MikeTheWatchGuy** [comment]
Closing this....
Created a new Git repository for this project with the temporary name.... [wxFlexForms](https://github.com/MikeTheWatchGuy/wxFlexForms).  I may roll other GUI things into it to make it into a 'GUI' SDK down the road and that's when a name change would be in order.  lazyGUI?  

I WISH Python would address this missing GUI capability.  SIMPLE GUI so that anyone can have a windows program up and running quickly.  It's WEIRD nothing good exists that's simple and solid.

**Comment by JorjMcKie** [comment]
As I mentioned once:
When Python was created in the early 1990s, simply nothing was there like the "adult" packages Qt and wxWidgets. So they had to incorporate Tk in order to have at least *something*.

This has changed of course after more than 2 decades. But now there are several fractions, each fighting for their favorite - mainly the 2 mentioned above. If I understand the situation correctly, this is why things are not moving and standard Python continues to to be distributed with this GUI package for the poor, also called Tk.

Anyone (like you) creating something "simple" will have to decide whether to go for Qt or for wx. And this very decision singles out the candidate population for using it ...

**Comment by MikeTheWatchGuy** [comment]
Hmmmm….

Thanks for the re-reply 😊

I’m thinking now I should go with tkinter under FlexForm, if I ever want people to use it.

But, screw that… I do NOT want to do another GUI anything in tkinter.  And, while it’s fun to share, it really is for my own consumption.  The way almost all of my programs have worked so far, you can pull off the GUI part very easily.

I’m still thinking something very trivial to use is missing.

With my simple fixed-grid system, it’s possible and indeed easy, to re-create any dialog you want.  The complexity of the big-guys isn’t needed for the majority of us.

Of course, you’re the one that provided all that source code that got me started, so you’re way ahead.

Thanks again for listening and for your time

-mike-
